In [31]:
import pandas as pd
import numpy as np


imdb330 = pd.read_csv('D:\PycharmProjects\web_scraping\deneme_scrapy\imdblist\imdb330.csv')
imdb330_df = pd.DataFrame(imdb330)


imdb330_df.rename(columns = {"country":"Country", "date": "Date", "director": "Director", 
                                          "film": "Film", "rate": "Rate", "stars": "Stars"}, inplace=True)

imdb330_df.reindex(columns=["Film","Date","Country","Rate","Director","Stars"])


imdb330_df.sort_values(by="Rate", ascending=False, inplace=True)
imdb330_df.set_index(np.arange(1,(len(imdb330_df))+1), inplace=True)


imdb330_df

,Country,Date,Director,Film,Rate,Stars
1,USA,14 October 1994,Frank Darabont,The Shawshank Redemption,9.3,"Tim Robbins,Morgan Freeman,Bob Gunton"
2,USA,24 March 1972,Francis Ford Coppola,The Godfather,9.2,"Marlon Brando,Al Pacino,James Caan"
3,USA,18 July 2008,Christopher Nolan,The Dark Knight,9.0,"Christian Bale,Heath Ledger,Aaron Eckhart"
4,USA,18 December 1974,Francis Ford Coppola,The Godfather: Part II,9.0,"Al Pacino,Robert De Niro,Robert Duvall"
5,Netherlands,1 December 2016,Alper Caglar,The Mountain II,8.9,"Caglar Ertugrul,Ufuk Bayraktar,Ahu Türkpençe"
...,...,...,...,...,...,...
314,Turkey,26 December 2015,Furkan Kopuz,Bilincsizler,7.4,"Nuray Guneci,Furkan Kopuz,Metin Cemal Aydin"
315,USA,17 December 2014,Peter Jackson,The Hobbit: The Battle of the Five Armies,7.4,"Ian McKellen,Martin Freeman,Richard Armitage"
316,USA,24 May 2002,Christopher Nolan,Insomnia,7.2,"Al Pacino,Robin Williams,Hilary Swank"
317,USA,25 April 2012,Faruk Aksoy,Conquest 1453,6.7,"Devrim Evin,Ibrahim Celikkol,Dilek Serbest"
318,Turkey,19 May 2013,Furkan Kopuz,Sekiz Cinayeti,6.0,"Furkan Kopuz,Ömer Faruk Kopuz,Ercan Kopuz"